### PR TITLE
argument names review

### PR DESCRIPTION
**Pull request by vladdez**

### CODE REVIEW

**Comment by behinger** [comment]
clapping-applause

big effort very nice! Ready to merge from my side :)

This is of course hugely breaking

**Comment by vladdez** [comment]
Cool, thanks! Will you press the button?
Also you can check kwargs pull request ;)

**Comment by vladdez** [comment]
the only "problem" unsolved plotData in plot_erp
it crashed after changing to "data", probably because of function data()

**Comment by behinger** [comment]
ah - missed that. data probably because of AlgebraOfGraphics.data

**Pull request merged**
