### PR TITLE
fix col/row/layout AoG pattern

### PR DESCRIPTION
**Pull request by behinger**

### CODE REVIEW

**Comment by vladdez** [comment]
What is achieved by these changes?
Makie.Mat4f looks awful after formatting

**Comment by behinger** [comment]
see #149  for what this fixes.

Sorry about the formatting, this is just what formatter puts out :S

**Comment by vladdez** [comment]
Could you please check it with this test

`@testset "ERP plot, colour groupping" begin
    plot_erp(results; mapping = (; color = :group))
end`

**Review by vladdez — COMMENTED** [review]
- fixed #149
- unit test for erp plot added

**Pull request merged**
