### PR TITLE
Kwargs error

### PR DESCRIPTION
**Pull request by vladdez**

### CODE REVIEW

**Comment by behinger** [comment]
giphy
looks good - so no problems with the kwargs afterall, just problems in docs/tests :)

**Comment by vladdez** [comment]
should i resolve and merge then?

**Comment by behinger** [comment]
nt sure what happened now. I thought I already merged it

**Comment by behinger** [comment]
ah sorry I confused myself.

**Comment by behinger** [comment]
yes resolve and merge :)

**Pull request merged**
