### PR TITLE
allow abstractvector in plot_topoplot

### PR DESCRIPTION
**Pull request by behinger**

### CODE REVIEW

**Comment by vladdez** [comment]
Could you write down a context and benefits of this PR? Maybe add some checking test?

**Comment by behinger** [comment]
right now topoplot(zeros(1:128) doesnt work because it is Float64

Something like a view(dataframe[1:10,1:10]) will also not work

**Comment by vladdez** [comment]
I created two tests and they both are failing

**Comment by behinger** [comment]
maybe specify some random positions?

**Comment by vladdez** [comment]
I though any function can work without kwargs

**Comment by vladdez** [comment]
I looked in the code
In current implementation any vector should have column names

**Comment by behinger** [comment]
how would topoplot work without positions?

**Comment by behinger** [comment]
yeah you have to wrap it with a eeg_matrix_to_dataframe - I thought you had implemented that by default - sorry

**Comment by vladdez** [comment]
Done:
- `AbstractDataFrame, AbstractVector `are allowed for data
- 2 additional tests are added

**Pull request merged**
